---
title: "Szakdolgozat"
author: "Császár Szabolcs"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    logo: logo.png
    theme: flatly
    source_code: https://github.com/cssz98/szakdolgozat
    favicon: favicon.gif
resource_files:
- folytonos/app.R
- diszkret/app.R
---


```{r head}
tags$style(HTML(".container-fluid , #navbar , a , .navbar-brand {background:   	#00a65a}"))
tags$style(HTML(".active a {background-image: linear-gradient(#00a65a, #18bc9c)}")) 
```

Nevezetes diszkrét eloszlások {data-icon="fa-chart-bar"}
======================================================================

```{r diszkret,echo=FALSE}

shinyAppDir(
 "./diszkret",
  options=list(
    width="100%", height="100%"
  )
)

```


Nevezetes folytonos eloszlások {data-icon="fa-chart-line"}
======================================================================

```{r folytonos,echo=FALSE}

shinyAppDir(
 "./folytonos",
  options=list(
    width="100%", height="100%"
  )
)

```



